# Generated by Django 2.0.4 on 2018-10-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='image',
            name='body',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
    ]
