# Generated by Django 2.0.4 on 2018-10-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_auto_20181010_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='word',
            new_name='words',
        ),
    ]
