# Generated by Django 2.0.4 on 2018-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_auto_20181010_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='words',
        ),
    ]
