# Generated by Django 2.0.4 on 2018-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_auto_20181010_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
